apiVersion: v1
kind: Service
metadata:
  name: dnsseeder-tcp
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 53
      targetPort: 8053
  selector:
    service: dnsseeder
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 104.197.5.231
